# Cluster Analysis using KMeans with n_clusters = 4

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
outage_df = pd.read_csv('outage_df_kmean.csv', index_col=0)
outage_df.head()

,Datetime Event Began,State Affected,NERC Region,Alert Criteria,Event Type,Demand Loss (MW),Number of Customers Affected,State Avg Temp (F),State Avg Windspeed (mph),State Avg Precipitation (mm),Monthly Net Energy for Load (GWh),Monthly Peak Hour Demand (MW),State Avg Snowfall (mm),KMeans Labels (4 clusters)
0,2018-01-02 10:00:00,New York,NPCC,Fuel supply emergencies that could impact elec...,System Operations,675.0,0.0,11.261429,11.499064,0.811386,63641.527716,110050.900000,0.0,3
1,2018-01-02 06:45:00,North Carolina,SERC,System-wide voltage reductions of 3 percent or...,Severe Weather,14998.0,0.0,18.694595,4.726667,0.000424,85958.000000,179134.000000,0.0,0
2,2018-01-12 13:08:00,Michigan,RF,Cyber event that causes interruptions of elect...,System Operations,41.0,23007.0,18.944706,15.835709,8.174586,76640.000000,137465.000000,0.0,3
3,2018-02-04 13:42:00,California,WECC,Physical attack that could potentially impact ...,Vandalism,9760.0,0.0,56.094913,1.118450,0.005626,66930.133379,127365.022436,0.0,0
4,2018-02-08 13:25:00,California,WECC,Electrical System Separation (Islanding) where...,System Operations,30.0,10900.0,56.660645,3.791818,0.001110,66930.133379,127365.022436,0.0,0

The below code will group the dataframe by the KMeans clusters and analyze the characteristics of each cluster.

In [13]:
grouped_df = outage_df.groupby('KMeans Labels (4 clusters)')
grouped_df.count()

,Datetime Event Began,State Affected,NERC Region,Alert Criteria,Event Type,Demand Loss (MW),Number of Customers Affected,State Avg Temp (F),State Avg Windspeed (mph),State Avg Precipitation (mm),Monthly Net Energy for Load (GWh),Monthly Peak Hour Demand (MW),State Avg Snowfall (mm)
KMeans Labels (4 clusters),,,,,,,,,,,,,
0,248,248,248,248,248,248,248,248,248,248,248,248,248
1,75,75,75,75,75,75,75,75,75,75,75,75,75
2,15,15,15,15,15,15,15,15,15,15,15,15,15
3,81,81,81,81,81,81,81,81,81,81,81,81,81

>By far, the largest cluster is cluster 0 and the smallest is cluster 2.  Let's dig into the features of each.

In [21]:
# show cross tab of NERC regions in each cluster
pd.crosstab(outage_df['KMeans Labels (4 clusters)'], outage_df['NERC Region'])

NERC Region                 FRCC  MRO  NPCC  RF  SERC  SPP RE  TRE  WECC
KMeans Labels (4 clusters)
0                              0   36     3  26    60       0    0   123
1                              7    0    11   1     0       6   49     1
2                              0    2     0   2     0       0    0    11
3                              0   13     4   8    44       0    0    12

>Most of the western outages are clustered in 0, while all the Texas and Florida outages are clustered in 1. Cluster 1 also contains all SPP outages which covers geographic areas consisting of the following states: Arkansas, Iowa, Kansas, Louisiana, Minnesota, Missouri, Montana, Nebraska, New Mexico, North Dakota, Oklahoma, South Dakota, Texas, and Wyoming.

In [24]:
# show cross tab of event type in each cluster
pd.crosstab(outage_df['KMeans Labels (4 clusters)'], outage_df['Event Type'])

Event Type,Cyber Event,Other,Severe Weather,System Operations,Transmission / Distribution Interruption,Vandalism
KMeans Labels (4 clusters),,,,,,
0,1,4,85,49,50,59
1,0,0,40,9,20,6
2,0,0,11,2,0,2
3,0,0,60,11,4,6

>Event types seem to be spread evenly throughout the clusters.

### Descriptive statistics for each cluster will be shown below.

In [39]:
# Show the descriptive statistics for each column for each cluster
pd.set_option('display.max_rows', None)
pd.options.display.float_format = '{:.2f}'.format
grouped_df.describe().T

KMeans Labels (4 clusters)                      0          1         2  \
Demand Loss (MW)                  count    248.00      75.00     15.00
                                  mean     737.78     669.55    540.07
                                  std     2791.72    1589.48   1531.06
                                  min        1.00       1.00     14.00
                                  25%       20.00      25.50     64.50
                                  50%       88.50     150.00    143.00
                                  75%      380.25     512.00    210.00
                                  max    33480.00   10000.00   6062.00
Number of Customers Affected      count    248.00      75.00     15.00
                                  mean   39352.86  134682.07  79451.07
                                  std    95669.35  527222.51  60877.58
                                  min        0.00       0.00      0.00
                                  25%        0.00       0.00  45100.00
                                  50%     3667.00    6102.00  67864.00
                                  75%    45777.25   58873.50 113315.00
                                  max   972000.00 4200000.00 230000.00
State Avg Temp (F)                count    248.00      75.00     15.00
                                  mean      56.24      59.01     33.96
                                  std       20.25      25.06      6.94
                                  min      -10.69      14.94     21.05
                                  25%       41.19      39.65     29.27
                                  50%       59.17      69.97     34.32
                                  75%       73.41      80.40     38.59
                                  max       89.11      87.54     45.53
State Avg Windspeed (mph)         count    248.00      75.00     15.00
                                  mean       5.95       8.03      9.35
                                  std        2.30       2.43      3.14
                                  min        0.89       2.46      5.18
                                  25%        4.31       6.50      7.92
                                  50%        5.97       8.04      8.17
                                  75%        7.65       9.11     10.17
                                  max       11.86      15.80     17.76
State Avg Precipitation (mm)      count    248.00      75.00     15.00
                                  mean       2.17       5.98     14.57
                                  std        3.55       9.66      7.02
                                  min        0.00       0.00      0.55
                                  25%        0.03       0.70     11.27
                                  50%        0.45       3.30     14.92
                                  75%        2.61       7.14     18.03
                                  max       18.15      64.67     31.43
Monthly Net Energy for Load (GWh) count    248.00      75.00     15.00
                                  mean   76390.04   35186.32  73221.31
                                  std     9204.46   11168.48   6652.26
                                  min    56183.50   16824.00  59390.00
                                  25%    69411.55   29095.56  69672.49
                                  50%    75823.36   31269.72  74404.82
                                  75%    82902.95   41121.05  79534.92
                                  max    98533.10   75194.04  80335.19
Monthly Peak Hour Demand (MW)     count    248.00      75.00     15.00
                                  mean  142655.02   69171.75 126260.69
                                  std    22907.19   19585.07  10845.26
                                  min    97314.00   36614.00  97314.00
                                  25%   124348.82   56264.78 124747.19
                                  50%   140981.49   69811.95 128013.16
                                  75%   160579.25   74375.85 130757.00
                                  max   209429.65  150546.70 141226.81
State Avg Snowfall (mm)           count    248.00      75.00     15.00
                                  mean       1.05       0.38     52.39
                                  std        3.49       0.81     18.16
                                  min        0.00       0.00     29.73
                                  25%        0.00       0.00     37.58
                                  50%        0.00       0.00     48.90
                                  75%        0.18       0.39     62.90
                                  max       34.49       5.41     84.71

KMeans Labels (4 clusters)                      3
Demand Loss (MW)                  count     81.00
                                  mean    2182.63
                                  std    14783.63
                                  min        2.00
                                  25%       48.00
                                  50%      166.00
                                  75%      436.00
                                  max   133200.00
Number of Customers Affected      count     81.00
                                  mean   56218.83
                                  std    95915.27
                                  min        0.00
                                  25%      327.00
                                  50%    24457.00
                                  75%    62000.00
                                  max   623358.00
State Avg Temp (F)                count     81.00
                                  mean      49.13
                                  std       21.48
                                  min        0.39
                                  25%       35.44
                                  50%       47.39
                                  75%       68.02
                                  max       80.99
State Avg Windspeed (mph)         count     81.00
                                  mean      12.82
                                  std        3.30
                                  min        6.32
                                  25%       10.61
                                  50%       12.46
                                  75%       14.70
                                  max       24.09
State Avg Precipitation (mm)      count     81.00
                                  mean      16.20
                                  std       15.94
                                  min        0.01
                                  25%        3.55
                                  50%       10.29
                                  75%       24.67
                                  max       64.58
Monthly Net Energy for Load (GWh) count     81.00
                                  mean   73202.56
                                  std     7953.72
                                  min    55680.52
                                  25%    67251.00
                                  50%    72355.00
                                  75%    79243.87
                                  max    89412.00
Monthly Peak Hour Demand (MW)     count     81.00
                                  mean  140937.34
                                  std    22760.09
                                  min   100374.35
                                  25%   123487.41
                                  50%   137465.00
                                  75%   155136.00
                                  max   193579.39
State Avg Snowfall (mm)           count     81.00
                                  mean       1.27
                                  std        3.59
                                  min        0.00
                                  25%        0.00
                                  50%        0.00
                                  75%        0.39
                                  max       18.62

>**Demand Loss:** By far, the largest demand losses are concentrated in cluster 3, however this seems to be due to a major outlier with an extremely high value of demand loss.  The medians are much closer together.
>**Number of Customers Affected:** Again, outliers cause the highest mean of this metric to be in cluster 1.  However, the medians are much more closely distributed.
>**State Avg Temp and State Avg Snowfall:** Cluster 2 seems to contain colder temperatures and larger amounts of snowfall.  Perhaps this is the defining characteristic of cluster 2.
>**State Avg Windspeed:** Cluster 3 seems to contain the outages with the highest associated windspeed.
>**State Avg Precipitation:** Cluster 2 seems to contain the highest amount of associated precipitation.  This is in line with this cluster being associated with the largest amount of snowfall.  Cluster 3 also seems to have large amounts of precipitation, although not as much as cluster 2.
>**Net Energy for Load:** Cluster 1 has the lowest load.  The others are pretty similar.
>**Energy Demand:** Cluster 1 has the lowest demand as well.  Other clusters are pretty similar.